#define UNKNOWN_APP_ID 999
#define DJIRC_APP_ID 1
#define LK_APP_ID 2
#define HIPNUC_IMU_CAN_APP_ID 3
#define DSHOT_APP_ID 4
#define DJICAN_APP_ID 5
#define VANILLA_PWM_APP_ID 6
#define EXTERNAL_PWM_APP_ID 7
#define MS5876_30BA_APP_ID 8
#define ADC_APP_ID 9
#define CAN_PMU_APP_ID 10

#define CAN_PORT_1 1
#define CAN_PORT_2 2

#define TIM_2 2
#define TIM_3 3

#define USART1 1
#define UART4 4
#define UART8 8

#define I2C3 3

slaves:
  - sn4587574:
      sdo_len: !uint16_t 2
      task_count: !uint8_t 1
      latency_pub_topic: !std::string '/ecat/sn4587574/latency'

      tasks:
        - app_1:
            sdowrite_task_type: !uint8_t 11
            pub_topic: !std::string '/rc'
            pdoread_offset: !uint16_t 0